name: Deploy 🚀
description: Deploy a container image to wacky
author: gergoszaszvaradi
inputs:
  name:
    description: The name of the container
    required: true
    type: string
  image:
    description: The container image to deploy
    required: true
    type: string
  token:
    description: The github token
    required: true
    type: string
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        repository: wacky-homes/apps
        ref: main
        token: ${{ inputs.token }}
    - name: Replace image tag
      uses: mikefarah/yq@master
      with:
        cmd: yq eval '.services.${{ inputs.name }}.image = ${{ inputs.image }}' -i compose.yaml
    - name: Commit changes
      shell: bash
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email ""
        git add .
        git commit -m "[release] ${{ inputs.name }} ${{ inputs.image }}"
        git push
