name: Docker Build
description: Build a Docker image
author: gergoszaszvaradi
inputs:
  image:
    description: The container image to build
    required: true
    type: string
  version:
    description: The version of the image
    required: true
    type: string
  dockerfile:
    description: The path to the Dockerfile
    required: true
    type: string
  context:
    description: The build context
    required: true
    type: string
runs:
  using: composite
  steps:
    - name: Build Docker image
      run: |
        docker build -t ${{ inputs.image }}:${{ inputs.version }} -f ${{ inputs.dockerfile }} ${{ inputs.context }}
      shell: bash
